# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toast.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notification(object):
    def setupUi(self, notification):
        notification.setObjectName("notification")
        notification.resize(300, 80)
        notification.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        notification.setStyleSheet("/* 基础通知样式 - 默认主题 \n"
"#notification {\n"
"    background-color: transparent;\n"
"    border-radius: 24px;\n"
"    box-shadow: 0 2px 10px rgba(94, 255, 235, 0.85);\n"
"    border: 2px solid #6F6F6F;\n"
"    padding: 12px 16px;\n"
"    margin: 0px;\n"
"    min-width: 300px;\n"
"    max-width: 400px;\n"
"    color: #1b2d1b;\n"
"    font-family: \'Microsoft YaHei\', \'Segoe UI\', Arial, sans-serif;\n"
"}\n"
"\n"
"#notification::hover {\n"
"    border: 3px solid #A0A0A0;\n"
"}\n"
"*/\n"
"#notification {\n"
"    font-family: \'Microsoft YaHei\', \'Segoe UI\', Arial, sans-serif;\n"
"}\n"
"\n"
"/* 标题样式 */\n"
"#notification #lbl_title {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 11, 47, 255), stop:0.649007 rgba(67, 0, 114, 255), stop:0.836645 rgba(115, 61, 125, 255), stop:0.990157 rgba(209, 70, 158, 255));\n"
"    padding: 4px;\n"
"    font: 20px \"黑体\";\n"
"    font-weight: bold;\n"
"    color: rgb(10, 185, 188);\n"
"    border-top: 2px solid rgb(219,88,173);\n"
"    border-right: 2px solid rgb(219,88,173);\n"
"    border-top-right-radius: 30px;\n"
"}\n"
"\n"
"/* 消息内容样式 */\n"
"#notification #lbl_message {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 11, 47, 255), stop:0.649007 rgba(67, 0, 114, 255), stop:0.836645 rgba(115, 61, 125, 255), stop:0.990157 rgba(209, 70, 158, 255));\n"
"    padding: 4px;\n"
"    font-size: 15px;\n"
"    color: rgb(7, 130, 132);\n"
"    border-bottom: 2px solid rgb(219,88,173);\n"
"    border-right: 2px solid rgb(219,88,173);\n"
"    border-bottom-right-radius: 30px;\n"
"}\n"
"\n"
"/* 不同消息等级样式 */\n"
"#notification #lbl_level {\n"
"    background: #ffb503;\n"
"    min-width: 32px;\n"
"    border-left: 2px solid rgb(219,88,173);\n"
"    border-top: 2px solid rgb(219,88,173);\n"
"    border-bottom: 2px solid rgb(219,88,173);\n"
"    border-top-left-radius: 30px;\n"
"    border-bottom-left-radius: 30px;\n"
"}\n"
"\n"
"/* 关闭按钮样式 */\n"
"#notification #btn_close {\n"
"    background: rgba(129, 0, 193, 100);\n"
"    border: 0px solid;\n"
"    border-radius: 12px;\n"
"    color: #888888;\n"
"    margin-left: 0px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"#notification #btn_close:hover {\n"
"    background: rgba(129, 0, 193, 150);\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(notification)
        self.horizontalLayout.setContentsMargins(1, 1, 10, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_level = QtWidgets.QLabel(notification)
        self.lbl_level.setMaximumSize(QtCore.QSize(10, 16777215))
        self.lbl_level.setBaseSize(QtCore.QSize(3, 0))
        self.lbl_level.setText("")
        self.lbl_level.setObjectName("lbl_level")
        self.horizontalLayout.addWidget(self.lbl_level)
        self.content_layout = QtWidgets.QVBoxLayout()
        self.content_layout.setContentsMargins(0, -1, 10, 0)
        self.content_layout.setSpacing(0)
        self.content_layout.setObjectName("content_layout")
        self.lbl_title = QtWidgets.QLabel(notification)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setWordWrap(True)
        self.lbl_title.setObjectName("lbl_title")
        self.content_layout.addWidget(self.lbl_title)
        self.lbl_message = QtWidgets.QLabel(notification)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setUnderline(False)
        self.lbl_message.setFont(font)
        self.lbl_message.setWordWrap(True)
        self.lbl_message.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lbl_message.setObjectName("lbl_message")
        self.content_layout.addWidget(self.lbl_message)
        self.content_layout.setStretch(0, 1)
        self.content_layout.setStretch(1, 20)
        self.horizontalLayout.addLayout(self.content_layout)
        self.btn_close = QtWidgets.QPushButton(notification)
        self.btn_close.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/close"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(15, 15))
        self.btn_close.setAutoRepeat(False)
        self.btn_close.setAutoDefault(False)
        self.btn_close.setDefault(False)
        self.btn_close.setFlat(False)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)

        self.retranslateUi(notification)
        QtCore.QMetaObject.connectSlotsByName(notification)

    def retranslateUi(self, notification):
        _translate = QtCore.QCoreApplication.translate
        notification.setWindowTitle(_translate("notification", "Form"))
        self.lbl_title.setText(_translate("notification", "标题"))
        self.lbl_message.setText(_translate("notification", "这是一条消息qqqq"))
import toast_rc
